variable "instance_type" {}
variable "tags" {}
variable "pubsg_name" {}
variable "key_name" {}
variable "listedAZs" {}
variable "sg_id" {}
variable "tag" {}
variable "targetARN" {}
variable "ami_id" {}